### ISSUE TITLE
Nuxt.config.js doesn't escape single quotes in project description

### ISSUE THREAD

**Issue by foundryspatial-duncan** [vuetifyjs/nuxt#14]
If you use a single quote in your project description during the vue-cli init,
(for example: `Foobar Company's New Website`), 
Webpack will fail:
```
/Users/tomcruise/repos/my-project/nuxt.config.js:11
      { hid: 'description', name: 'description', content: 'Foobar Company's New Website' }
```
I dunno if vue-cli has an easy way of escaping strings like that, but others may stumble upon the issue as I just did.

**Comment by nekosaur** [comment]
Thank you for the info. This is however a limitation/bug in vue-cli, not this specific template.
