### ISSUE TITLE
[Bug report]  [Vue warn]: Injection "radio" not found.

### ISSUE THREAD

**Issue by ptitkiller** [vuetifyjs/nuxt#17]
**Steps to reproduce**
Im using v-radio-group and get following error:
 [Vue warn]: Injection "radio" not found.
**Versions**
vuetify: 0.17.2
nuxt: v1.0.0-rc11
![I[Vue warn]: Injection "radio" not found.](https://uphinhnhanh.com/images/2017/11/24/vuetify.png)
Thanks for support.

**Comment by nekosaur** [comment]
Which version of vue are you using?

**Comment by nekosaur** [comment]
This is because v-radio-group and v-radio uses optional injects which is a feature introduced in vue 2.5.0, while nuxt 1.0.0-rc11 depends on vue 2.4.2
