### ISSUE TITLE
vuetify@0.17.3 requires a peer of vue@^2.5.0 

### ISSUE THREAD

**Issue by besnikh** [vuetifyjs/nuxt#19]
npm WARN vuetify@0.17.3 requires a peer of vue@^2.5.0 but none is installed. You must install peer dependencies yourself.

Should I add myself or what's wrong ?

**Comment by nzxt** [comment]
Yes, after install you need to execute: `npm i vue vue-server-renderer vue-template-compiler`, and then vuetifyjs 0.17.x works fine.

**Comment by besnikh** [comment]
@nzxt thnx, that helped :)
