### ISSUE TITLE
[Vue warn]: Unknown custom element: <v-col>

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/nuxt#2]
**Steps to reproduce**
Use the "NUXT Quick Start", click on link to the inspire page, then click on back to the Welcome page.

**Versions**
vuetify: 0.12.6
nuxt: v1.0.0-alpha.3

**What is actually happening ?**
![9ef8be04-47c5-11e7-92a1-c53f5d1abaae](https://user-images.githubusercontent.com/13983663/26908978-5e67e32a-4bd4-11e7-80ae-c793860d137d.png)

Originally, this issue was opened in https://github.com/vuetifyjs/vuetify/issues/680

**Comment by johnleider** [comment]
Looks like one slipped through dev, I'll get it fixed.
