### ISSUE TITLE
Replace deprecated 'babel-preset-es2015' with 'babel-preset-env'

### ISSUE THREAD

**Issue by nzxt** [vuetifyjs/nuxt#20]
Scaffold project `vue init vuetifyjs/nuxt`
After install run `npm i`
In console you can see warn:
> npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

Please, update template!

**Comment by nekosaur** [comment]
Should be fixed with latest template
