### ISSUE TITLE
undefined custom elements

### ISSUE THREAD

**Issue by codeistalk** [vuetifyjs/nuxt#24]
![3](https://user-images.githubusercontent.com/35674135/36019527-29c34416-0db2-11e8-8a92-f18f4c034bb8.png)

**Comment by LuckySphinX** [comment]
Maybe, you've chosen the a la carte option when initiating the project? Then you have to go to the plugins folder and modify the vuetify.js file. Add the components you want to use.

**Comment by nekosaur** [comment]
@LuckySphinX is correct.
