### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ekoeryanto** [vuetifyjs/nuxt#28]
First install with latest vuetify (1.0.2) 
giving `Cannot read property 'split' of undefined`

setting REQUIRED_VUE environment to 2.5.0 fix the issue

```bash
// window
set REQUIRED_VUE=2.5.0
yarn dev
// linux
REQUIRED_VUE=2.5.0 yarn dev
```

**Comment by johnleider** [comment]
We are tracking the issue, please do not make multiple ones, thank you!
