### ISSUE TITLE
Transitions don't work

### ISSUE THREAD

**Issue by dzift** [vuetifyjs/nuxt#3]
In a freshly installed template `<nuxt />` is inside a transition component, yet there is no transition going on between the routes.

**Comment by gustavoguichard** [comment]
@dzift , I removed the `<v-slide-y-transition>` component from `./layouts/default.vue` and then I was able to set my own transitions like they do in Nuxt docs.
I hope that helps.

**Comment by dzift** [comment]
Yes I did the same thing. Figured Nuxt takes over the routing so Vuetify's transitions don't trigger at all. It would be cool to see it work like that though.

**Comment by johnleider** [comment]
It's best to use the default functionality provided by nuxt when transitioning pages. If you want to use one of vuetify's specific transitions, you can reference them by name when declaring your transitions in nuxt, 'slide-x-transition', 'scale-transition', etc.
