### ISSUE TITLE
npm run dev fails on npx create-nuxt-app with vuetify

### ISSUE THREAD

**Issue by MalikFaizanZafar** [vuetifyjs/nuxt#33]
This is the ERROR

![vuetify error](https://user-images.githubusercontent.com/29966551/37591013-e7d67256-2b8b-11e8-9cfa-ffb6fef1f1cf.PNG)

**Comment by skozzii** [comment]
I have the same issue, just did a fresh clone from the github repo and npm install/ npm run dev.  Mine will launch the server, but wont load the site or navigate to it 

>  ERROR  Failed to compile with 1 errors                                                                                                                                                                                        09:35:43
 error  in ./assets/style/app.styl

Module build failed: ValidationError: PostCSS Loader Invalid Options
options['useConfigFile'] is an invalid additional property

>

**Comment by MalikFaizanZafar** [comment]
that solved the problem....thanks skozzii

**Comment by koresar** [comment]
The original bug in postcss-loader was fixed. Thus this issue is fixed too. Can be closed.
