### ISSUE TITLE
Could I get an example on how to override stylus vars?

### ISSUE THREAD

**Issue by joostdecock** [vuetifyjs/nuxt#36]
I'm trying to understand how to override stylus vars, but the vuetify documentation assumes it's loaded in your app directly, and the extra nuxt abstraction is making things a bit too opaque for my limited understanding.

While I can override the theme settings in the config, this is limited to colors, and I would like to tweak a few other things like fonts and sizes and so on.

I understand that I should add the stylus webpack loader and then load my .styl file with variable overrides before loading the vuetify .stil files, but what that sounds logical enough, I'm afraid I need some pointers on how to make that actually happen for this nuxt version of vuetify.

As such, I would really appreciate a pointer on how to accomplish this.

**Comment by redijedi** [comment]
Did you ever find any pointers?

**Comment by joostdecock** [comment]
@redijedi see here: https://github.com/freesewing/site/blob/v2/nuxt/assets/style/freesewing.styl
