### ISSUE TITLE
package.json is not filled with user content

### ISSUE THREAD

**Issue by ishitatsuyuki** [vuetifyjs/nuxt#5]
It has hardcoded placeholders. Please change them to template instead.

**Comment by ishitatsuyuki** [comment]
Also README.

**Comment by johnleider** [comment]
Should be fixed, if README is still messed up, open a new issue please.

**Comment by ishitatsuyuki** [comment]
I mean, [this](https://github.com/vuetifyjs/nuxt/blob/master/template/README.md) should also have template placeholders...
