### ISSUE TITLE
IMPORTANT: This template is deprecated - nuxt-community/starter-template

### ISSUE THREAD

**Issue by Codefa** [vuetifyjs/nuxt#63]
@johnleider Please See that the nuxt-community/starter-template is deprecated 
must use [](url)https://github.com/nuxt/create-nuxt-app to crate app create-nuxt-ap have vuetify option it just need to update to latest version and some changes in layout.vue,index.vue hope you consider it

**Comment by johnleider** [comment]
I haven't been heavily involved in nuxt support within the framework. Could you provide some help with this?

**Comment by Codefa** [comment]
@johnleider I don't have much time anyway i will help my suggestion is, for nuxt+vuetify use create-nuxt-app and select vuetify as the UI currently there is no other starter template for us to create a new one..

**Comment by XanderLuciano** [comment]
I could try and help out with this.

Looks like the create-nuxt-app with vuetify is lacking an option for a la carte. Should future development just be directed towards create-nuxt-app? Or is there still interest in keeping a vuetify specific template up to date?

**Comment by Codefa** [comment]
We should contribute in create-nuxt-app work on improve vuetify

**Comment by Codefa** [comment]
Sorry for closing this issue I decided to work on this same repository to continue this as our **vuetify nuxt template officially**

**Comment by Codefa** [comment]
#67 fixed in this PR
