### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by nimonian** [vuetifyjs/nuxt#72]
After downloading, I `cd` into the project directory and run `npm install`. I get a syntax error from `package.json`.

I assume this is because I chose `N` for a-la-carte components and therefore did not get `vue-loader`, leaving a trailing comma after `"vuetify": "^1.3.3",` in the following section of `package.json`
```
  "dependencies": {
    "nuxt": "^2.2.0",
    "vuetify": "^1.3.3",
    {{#alacarte}}
    "vuetify-loader": "^1.0.5"
    {{/alacarte}}
  },
```
Could it be as simple as moving `vuetify-loader` with a comma to the top of the dependencies?

**Comment by Codefa** [comment]
@nimonian Thanks for inform this i did a PR to fixx it,
for now you can just remove the trailing comma ( , ) after vuetify-loader then try npm i
